### ISSUE TITLE
[enhancement] Publish releases

### ISSUE THREAD

**Issue by raneq** [devjatkin/sphinx#16]
Hello,

We are using your role at [a playbook we are preparing](https://github.com/coopdevs/donalo) but we feel a bit unsafe downloading unversioned roles. Meaning that from one `ansible-galaxy install` to another, this role can be different with no easy way to see if there are any changes.

Have you considered doing so? It takes little time and improves a lot the reliability.

Thank you!

**Comment by piotrkochan** [comment]
Bump

**Comment by devjatkin** [comment]
Hello there,

I've updated role today and created a version/tag as well https://github.com/devjatkin/sphinx/releases/tag/1.0.0

I hope that exactly a thing you've been asking for

**Comment by raneq** [comment]
> Hello there,
> 
> I've updated role today and created a version/tag as well https://github.com/devjatkin/sphinx/releases/tag/1.0.0
> 
> I hope that exactly a thing you've been asking for

maybe it's of your interest @sauloperez
