### ISSUE TITLE
Multiple attributes with the same name not generated properly

### ISSUE THREAD

**Issue by xlr-8** [devjatkin/sphinx#6]
Hello,

I have noticed that your playbooks work really well, except when you have for example:
```
      sql_attr_uint: sphinx_internal_id
      sql_attr_uint: sphinx_deleted
      sql_attr_uint: closed
```

Which is a syntax allowed by sphinx (src: http://sphinxsearch.com/docs/current.html#conf-sql-attr-uint), but the data is replaced instead of appended.

So we should have:
```
      sql_attr_uint = sphinx_internal_id
      sql_attr_uint = sphinx_deleted
      sql_attr_uint =  closed
```

But end up with:
```
      sql_attr_uint =  closed
```

I guess that the template writing is the faulty one:
https://github.com/devjatkin/sphinx/blob/fa587eac6fd6e4cd275ea4737d4daee45a03f6ca/templates/conf.d_sources.conf.jn2

Kind regards,

**Comment by devjatkin** [comment]
Nice feature! It works very well as for me.

Thank you for your pull request.
